apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan4us
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qas
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qas
    spec:
      containers:
      - name: plan4us
        image: swr.la-south-2.myhuaweicloud.com/workshop02/plan4us:$BUILD_NUMBER
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: default-secret